# Generated by Django 5.2.3 on 2025-06-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=20, unique=True)),
                ('sender', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=255)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando coleta'), ('TRANSITO', 'Em trânsito'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], default='AGUARDANDO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
